# -*- coding: utf-8 -*-
"""cas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrdKnUbg91ATea3qJ_Gk8L99oSB2traT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

url = "https://raw.githubusercontent.com/JUAN-32/datamining/refs/heads/main/archivo2/Prestige_modificado.csv"

df = pd.read_csv(url)
df = pd.read_csv(url, sep=';')

# LIMPIEZA DE NOMBRES DE COLUMNAS

df.columns = df.columns.str.strip()

df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(
    " ",
    "_"
)

print("===================================")
print("COLUMNAS DEL DATASET")
print("===================================")

print(df.columns)

# VERIFICAR COLUMNAS IMPORTANTES


columnas_requeridas = [
    'education',
    'income',
    'women',
    'prestige',
    'census',
    'type_num'
]

print("\n===================================")
print("VERIFICACIÓN DE COLUMNAS")
print("===================================")

for columna in columnas_requeridas:

    if columna in df.columns:
        print(f"{columna} --> OK")

    else:
        print(f"{columna} --> NO EXISTE")

# CONVERTIR COLUMNAS A NUMÉRICAS

for columna in columnas_requeridas:

    if columna in df.columns:

        df[columna] = pd.to_numeric(
            df[columna],
            errors='coerce'
        )

# INSPECCIÓN INICIAL
print("\n===================================")
print("DIMENSIONES DEL DATASET")
print("===================================")

print(df.shape)

print("\n===================================")
print("PRIMERAS FILAS")
print("===================================")

print(df.head())

print("\n===================================")
print("INFORMACIÓN GENERAL")
print("===================================")

print(df.info())

print("\n===================================")
print("VALORES NULOS")
print("===================================")

print(df.isnull().sum())

print("\n===================================")
print("DUPLICADOS")
print("===================================")

print(df.duplicated().sum())

print("\n===================================")
print("ESTADÍSTICA DESCRIPTIVA")
print("===================================")

print(df.describe())

# ELIMINAR FILAS CON NULOS EN VARIABLES CLAVE

df = df.dropna(
    subset=columnas_requeridas
)

# REVISIÓN DE VALORES ATÍPICOS

variables_numericas = df.select_dtypes(
    include=['int64', 'float64']
).columns

print("\n===================================")
print("REVISIÓN DE VALORES ATÍPICOS")
print("===================================")

for columna in variables_numericas:

    media = df[columna].mean()

    desviacion = df[columna].std()

    limite_inferior = media - (
        2 * desviacion
    )

    limite_superior = media + (
        2 * desviacion
    )

    atipicos = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    print("\n-----------------------------------")
    print("Variable:", columna)
    print("-----------------------------------")

    print(
        "Media:",
        round(media, 2)
    )

    print(
        "Desviación estándar:",
        round(desviacion, 2)
    )

    print(
        "Límite inferior:",
        round(limite_inferior, 2)
    )

    print(
        "Límite superior:",
        round(limite_superior, 2)
    )

    print(
        "Cantidad de atípicos:",
        len(atipicos)
    )

# MATRIZ DE CORRELACIÓN
variables_numericas = df.select_dtypes(
    include=['int64', 'float64']
)

matriz_correlacion = variables_numericas.corr()

print("\n===================================")
print("MATRIZ DE CORRELACIÓN")
print("===================================")

print(
    matriz_correlacion.round(3)
)

print("\n===================================")
print("CORRELACIONES CON PRESTIGE")
print("===================================")

print(
    matriz_correlacion['prestige']
    .sort_values(ascending=False)
    .round(3)
)

# VISUALIZACIONEs
# ============================================
# EDUCATION VS PRESTIGE
# ============================================

plt.figure(figsize=(8,5))

plt.scatter(
    df['education'],
    df['prestige']
)

plt.xlabel('Education')

plt.ylabel('Prestige')

plt.title(
    'Relación entre Education y Prestige'
)

plt.grid(True)

plt.show()

# INCOME VS PRESTIGE
# ============================================

plt.figure(figsize=(8,5))

plt.scatter(
    df['income'],
    df['prestige']
)

plt.xlabel('Income')

plt.ylabel('Prestige')

plt.title(
    'Relación entre Income y Prestige'
)

plt.grid(True)

plt.show()

# PRESTIGE POR TIPO
promedio_tipo = df.groupby(
    'type_num'
)['prestige'].mean()

plt.figure(figsize=(8,5))

promedio_tipo.plot(kind='bar')

plt.xlabel('Type')

plt.ylabel(
    'Promedio de Prestige'
)

plt.title(
    'Prestige promedio por tipo de ocupación'
)

plt.grid(True)

plt.show()

# K-MEANS
# ============================================

columnas_cluster = [
    'education',
    'income',
    'women',
    'prestige',
    'type_num'
]

X = df[columnas_cluster].copy()

# ESCALAMIENTO
escalador = StandardScaler()

X_escalado = escalador.fit_transform(X)

# K-MEANS CON 4 CLÚSTERES
modelo_k4 = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df['cluster_4'] = modelo_k4.fit_predict(
    X_escalado
)

print("\n===================================")
print("CENTROIDES K=4")
print("===================================")

print(
    df.groupby('cluster_4')[
        columnas_cluster
    ].mean().round(2)
)

# K-MEANS CON 5 CLÚSTERES
modelo_k5 = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

df['cluster_5'] = modelo_k5.fit_predict(
    X_escalado
)

print("\n===================================")
print("CENTROIDES K=5")
print("===================================")

print(
    df.groupby('cluster_5')[
        columnas_cluster
    ].mean().round(2)
)

# REGISTROS POR CLÚSTER
print("\n===================================")
print("REGISTROS POR CLÚSTER K=4")
print("===================================")

print(
    df['cluster_4']
    .value_counts()
)

print("\n===================================")
print("REGISTROS POR CLÚSTER K=5")
print("===================================")

print(
    df['cluster_5']
    .value_counts()
)

# VISUALIZACIÓN DE CLÚSTERES
plt.figure(figsize=(8,6))

plt.scatter(
    df['income'],
    df['prestige'],
    c=df['cluster_4']
)

plt.xlabel('Income')

plt.ylabel('Prestige')

plt.title(
    'Clusterización K=4'
)

plt.grid(True)

plt.show()

# EXPORTAR RESULTADOS
df.to_csv(
    'Prestige_resultados.csv',
    index=False
)

print("\n===================================")
print("ARCHIVO EXPORTADO CORRECTAMENTE")
print("===================================")